[package]
name = "migrant"
version = "0.11.5"
authors = ["James Kominick <james@kominick.com>"]
description = "CLI Database migration management for postgres, sqlite, mysql"
repository = "https://github.com/jaemk/migrant"
readme = "README.md"
keywords = ["database", "migration", "postgres", "sqlite", "mysql"]
categories = ["command-line-utilities", "database", "development-tools"]
license = "MIT"
exclude = [
    "/ci/*",
    "/migrations/*",
    "/db/*",
    "Migrant.toml",
    ".travis.yml",
]

[dependencies]
clap = "2"
error-chain = "0.11"
migrant_lib = { version = "0.20" }
self_update = { version = "0.4", optional = true }
rusqlite = { version = "0.14", optional = true, features = ["bundled"] }

[dev-dependencies]
assert_cli = "0.5"

[features]
default = []
sqlite = ["migrant_lib/d-sqlite", "rusqlite"]
postgres = ["migrant_lib/d-postgres"]
mysql = ["migrant_lib/d-mysql"]
update = ["self_update"]
integration_tests = []

